#!/bin/bash

clang -print-file-name=libasan.so
export ASAN_OPTIONS="leak_check_at_exit=false"
export LD_PRELOAD="$(clang -print-file-name=libasan.so) $(pwd)/libluajit.so $(pwd)/librosaserver.so"
./subrosadedicated.x64